-- Ejecutar una sola vez en Supabase SQL Editor.

insert into storage.buckets (id, name, public)
values ('galeria', 'galeria', true)
on conflict (id) do update set public = true;

create table if not exists public.fotos (
  id bigint generated by default as identity primary key,
  url text not null,
  created_at timestamptz not null default now()
);

alter table public.fotos enable row level security;

create policy "fotos visibles para todos"
on public.fotos for select
using (true);

create policy "fotos insertables con clave publicable"
on public.fotos for insert
to anon, authenticated
with check (true);

create policy "galeria visible para todos"
on storage.objects for select
using (bucket_id = 'galeria');

create policy "galeria permite cargas"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'galeria');
